version: '3.8'

services:
  audio-worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hey-listen-audio-worker

    restart: unless-stopped

    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-hey-listen-transcriptions}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - VECTOR_DIMENSION=${VECTOR_DIMENSION:-384}
      - MAX_RECORDS=${MAX_RECORDS:-1000}
      - WHISPER_MODEL=${WHISPER_MODEL:-tiny}
      - CHUNK_DURATION=${CHUNK_DURATION:-5}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}

    volumes:
      - ./.env:/app/.env:ro

    devices:
      - /dev/snd:/dev/snd  # ALSA sound devices (Linux)

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
